### PR TITLE
Create API Documentation with Flasgger

### PR DESCRIPTION
**Pull request by meshnesh**
# What does this PR do?

* Updates UI feedback
* Implements API documenation using Flassger
* Updates requirement.txt file

## Makes sure the above are implemented and working

How should this be manually tested?

* clone repo, cd to Bright-Events
* run app python3 run.py
* open the [API Docs](http://localhost:5000/apidocs) offline
* test online [API Docs](http://bright-events.herokuapp.com/apidocs)

### CODE REVIEW

**Comment by frankip** [comment]
great API documentation

**Comment by NaomiMariga** [comment]
- Good documentation, keep it up
##### Question
- What is the work of the dummy data in the file app/user_data.py and app/data.py?

**Comment by meshnesh** [comment]
@NaomiMariga  the dummy data in both files `app/user_data.py` and `app/data.py` help me in testing my API functions and endpoints, how they will behave with actual data

**Comment by NaomiMariga** [comment]
- I see. Good work

**Pull request merged**
